name: Publish

on:
  push:
    branches:
    - source

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Set git configuration
      run: |
        git config --global user.email "gh-actions@amphoradata.com"
        git config --global user.name "GitHub Actions"
    - name: npm install, build, and publish
      run: |
        pushd website
        npm install
        npm run build
        GIT_USER=amphoradata CURRENT_BRANCH=source USE_SSH=false npm run publish-gh-pages
        popd
      env:
        CI: true
