name: Publish

on:
  push:
    branches:
    - docs_v2

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Set git configuration
      run: |
        git config --global user.email "gh-actions@amphoradata.com"
        git config --global user.name "GitHub Actions"
    - uses: webfactory/ssh-agent@v0.1.1
      with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
    - uses: borales/actions-yarn@v2.1.0
      name: Yarn install
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.1.0
      name: Yarn build
      with:
        cmd: build # will run `yarn install` command
    - uses: borales/actions-yarn@v2.1.0
      name: Yarn deploy and publish
      with:
        cmd: deploy # will run `yarn install` command
      env:
        GIT_USER: amphoradata
        USE_SSH: true
